name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.803
      - name: Build with dotnet
        run: dotnet build src/**/*.csproj --configuration Release
      - name: Run Lambda Unit Tests
        run: dotnet test test/**/*.Tests.csproj
      - name: Publish Code
        run: dotnet publish src/*.Functions/*.csproj --configuration Release
      - name: cdk deploy
        uses: two4suited/aws-cdk-dotnet-github-action@master
        with:
          cdk_subcommand: 'deploy'
          actions_comment: false
          cdk_requireapproval: 'never'
          working_dir: 'infrastructure'
          cdk_version: '1.27.0'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-west-2'
